/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vqyxkrvypgbkokinhbnd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxeXhrcnZ5cGdia29raW5oYm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1MDkzNDQsImV4cCI6MjA5NjA4NTM0NH0.NbmNxqesRC92TsQ-KVj0kJI2mrsSZB3N2-YX6yiQ4fM"